# Generated by Django 2.2 on 2020-12-15 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=30, verbose_name='area')),
                ('village', models.CharField(blank=True, max_length=30, verbose_name='village')),
                ('district', models.CharField(blank=True, max_length=30, verbose_name='district')),
                ('whether', models.CharField(blank=True, max_length=30, verbose_name='whether')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
