# Generated by Django 2.2 on 2021-01-16 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_lat_long', jsonfield.fields.JSONField(default=dict)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_geo_tag', to='farms.Farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_geo_tag', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
