# Generated by Django 2.2 on 2021-03-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_geotag'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='acres',
            field=models.CharField(blank=True, max_length=30, verbose_name='acres'),
        ),
        migrations.AddField(
            model_name='farm',
            name='geo',
            field=models.CharField(blank=True, max_length=30, verbose_name='geo'),
        ),
        migrations.AddField(
            model_name='farm',
            name='soil_health',
            field=models.IntegerField(blank=True, default=None, verbose_name='Soil Health'),
            preserve_default=False,
        ),
    ]
