# Generated by Django 2.2 on 2021-03-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_farm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='acres',
            field=models.IntegerField(blank=True, max_length=30, verbose_name='acres'),
        ),
    ]
