# Generated by Django 2.2 on 2021-03-04 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0005_auto_20210304_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='geo',
        ),
    ]
