# Generated by Django 2.2 on 2021-03-04 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0006_remove_farm_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='geo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='geo', to='farms.GeoTag'),
            preserve_default=False,
        ),
    ]
