# Generated by Django 2.2 on 2021-03-05 16:44

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0007_farm_geo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='geo',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='GeoTag',
        ),
    ]
