# Generated by Django 2.2 on 2021-03-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0009_district_vilage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.CharField(blank=True, max_length=30, verbose_name='code'),
        ),
    ]
