image: alpine:latest
build:
  script:
    - touch foo.txt
  artifacts:
    paths:
    -  foo.txt



server_ssh:
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - scp -o StrictHostKeyChecking=no foo.txt ubuntu@ec2-34-222-26-89.us-west-2.compute.amazonaws.com:/home/ubuntu
    - ls
    
#pysetup:
#     image: python:3.6
#      script:
#        - python --version
#        - apt install python3-venv 
#       - source venv/bin/activate
