#build:
#  image: alpine
#  before_script:
#    - apk add zip
#  script:
#    - mkdir public
#    - touch public/index.html
#    - echo "<h1>New deployment<h1>" >> public/index.html
#    - zip -r public.zip public
#  artifacts:
#    paths:
#      - public.zip

deploy:
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
 #   - scp -o StrictHostKeyChecking=no public.zip ubuntu@ec2-34-222-26-89.us-west-2.compute.amazonaws.com:/home/ubuntu
    - ssh -io StrictHostKeyChecking=no ubuntu@ec2-34-222-26-89.us-west-2.compute.amazonaws.com 
    - ls
