image: ubuntu
before_script:
  # Setup SSH deploy keys
   - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
   - eval $(ssh-agent -s)
   - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh
   - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
stages:
    - test
#    - build

server_ssh:
     stage: test
     environment:
          name: staging
          url: ec2-34-213-177-214.us-west-2.compute.amazonaws.com
     script:
        - ssh ubuntu@ec2-34-213-177-214.us-west-2.compute.amazonaws.com "cd jishoy/farmers-app/; git pull origin develop ;cd; source env/bin/activate ; cd jishoy/farmers-app; pip3 install -r requirements.txt; cd ~/jishoy/farmers-app/farmersapp ; python manage.py migrate;pkill gunicorn ; sudo systemctl daemon-reload; sudo systemctl start gunicorn ;" 
        - pwd
        - cd  
        
