image: alpine:latest
build:
  before_script:
    - apk add zip
  script:
    - mkdir jishoy
    - touch jishoy/index.html
    - echo "<h1>New deployment<h1>" >> jishoy/index.html
    - zip -r jishoy.zip jishoy
  artifacts:
    paths:
     -  jishoy.zip



server_ssh:
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -o StrictHostKeyChecking=no jishoy.zip ubuntu@ec2-34-222-26-89.us-west-2.compute.amazonaws.com:/home/ubuntu
    
    
#pysetup:
#     image: python:3.6
#      script:
#        - python --version
#        - apt install python3-venv 
#       - source venv/bin/activate
