image: alpine
before_script:
     - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
     - eval $(ssh-agent -s)
     - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
     - mkdir -p ~/.ssh
     - mkdir -p ~/.ssh
     - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
    - test
#    - build

server_ssh:
     stage: test
     environment:
          name: staging
          url: ec2-34-221-196-124.us-west-2.compute.amazonaws.com
     script:
        - ssh jishoy@ec2-34-221-196-124.us-west-2.compute.amazonaws.com " git clone https://gitlab.com/johandurancerdas/gitlab-cicd-tutorial.git "
        - ls
