image: ubuntu:latest
variables:
#  WORK_DIR: ${CI_PROJECT_NAME}
#  BRANCH: ${CI_COMMIT_REF_NAME}
  REPO: https://gitlab.com/johandurancerdas/gitlab-cicd-tutorial.git
stages:
  - test
#  - deploy

test:
  stage: test
  environment: 
    name: Test
    url: ec2-34-222-26-89.us-west-2.compute.amazonaws.com
  before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh-add <(echo "$PRIVATE_KEY"| base64 -d)
    - rm -rf .git
    - ssh -o StrictHostKeyChecking=no ubuntu@ec2-34-222-26-89.us-west-2.compute.amazonaws.com "rm -rf ~/${WORK_DIR}; mkdir ~/${WORK_DIR}; git init; git clone ${REPO};"
