# Generated by Django 2.2 on 2021-01-04 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(blank=True, max_length=30, verbose_name='Crop Name')),
                ('exp_price', models.IntegerField(blank=True, verbose_name='Expected Price')),
                ('exp_yield', models.CharField(blank=True, max_length=30, verbose_name='Expected Yield')),
                ('exp_harvest_date', models.DateField(blank=True, verbose_name='Expected Harvest Date')),
                ('crop_images', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
                ('sell_flag', models.BooleanField(default=False)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_crop', to='farms.Farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_crop', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
