# Generated by Django 2.2 on 2021-01-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyrequest',
            name='machine',
            field=models.ManyToManyField(blank=True, related_name='crop_machine', to='crop.Machinery'),
        ),
    ]
