# Generated by Django 2.2 on 2021-01-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='exp_price',
            field=models.IntegerField(blank=True, max_length=30, verbose_name='Expected Price'),
        ),
    ]
