# Generated by Django 2.2 on 2021-01-25 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='activity',
        ),
        migrations.CreateModel(
            name='CropActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField(blank=True)),
                ('images', models.FileField(upload_to='images/')),
                ('crops', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crop.Crop')),
            ],
        ),
    ]
