# Generated by Django 2.2 on 2021-01-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0002_auto_20210107_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='crop_images',
            field=models.ImageField(upload_to='uploads/crop-images'),
        ),
    ]
