# Generated by Django 2.2 on 2021-01-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0002_auto_20210125_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='crop_image',
            field=models.FileField(default=None, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CropImage',
        ),
    ]
