# Generated by Django 2.2 on 2021-01-25 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0003_auto_20210125_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='activity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crop.CropActivity'),
        ),
    ]
