# Generated by Django 2.2 on 2021-01-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0003_auto_20210109_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='activity',
            field=models.TextField(blank=True),
        ),
    ]
