# Generated by Django 2.2 on 2021-01-02 06:03

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0003_auto_20210102_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='farm',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='continent', chained_model_field='continent', on_delete=django.db.models.deletion.CASCADE, to='farms.Farm'),
        ),
    ]
