# Generated by Django 2.2 on 2021-01-25 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0004_crop_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='activity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crop.CropActivity'),
        ),
    ]
