# Generated by Django 2.2 on 2021-01-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0004_crop_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='total_amt',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
    ]
