# Generated by Django 2.2 on 2021-01-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0005_auto_20210104_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='sell_flag',
            field=models.BooleanField(default=False),
        ),
    ]
