# Generated by Django 2.2 on 2021-01-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0005_auto_20210125_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='activity',
        ),
        migrations.AddField(
            model_name='crop',
            name='activity',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='crop.CropActivity'),
        ),
    ]
