# Generated by Django 2.2 on 2021-01-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0007_auto_20210125_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='activity',
            field=models.ManyToManyField(blank=True, default=None, editable=False, to='crop.CropActivity'),
        ),
    ]
