# Generated by Django 2.2 on 2021-01-11 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0007_auto_20210111_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyrequest',
            name='total_amt',
        ),
    ]
