# Generated by Django 2.2 on 2021-01-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0008_auto_20210125_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='activity',
        ),
    ]
