# Generated by Django 2.2 on 2021-01-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0009_buyrequest_total_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyrequest',
            name='total_amt',
            field=models.BigIntegerField(default=0),
        ),
    ]
