# Generated by Django 2.2 on 2021-01-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0009_remove_crop_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='crop_image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
