# Generated by Django 2.2 on 2021-02-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0010_auto_20210125_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
