# Generated by Django 2.2 on 2021-01-12 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0010_auto_20210111_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyrequest',
            name='total_amt',
        ),
    ]
