# Generated by Django 2.2 on 2021-03-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0011_buyrequest_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='acres',
            field=models.CharField(blank=True, max_length=30, verbose_name='Acres'),
        ),
        migrations.AddField(
            model_name='crop',
            name='harvest_days',
            field=models.IntegerField(blank=True, default=None, verbose_name='Harvest Days'),
            preserve_default=False,
        ),
    ]
