# Generated by Django 2.2 on 2021-03-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0012_auto_20210304_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinery',
            name='machine_image',
            field=models.FileField(blank=True, upload_to='machine_images/'),
        ),
        migrations.AddField(
            model_name='others',
            name='other_image',
            field=models.FileField(blank=True, upload_to='other_images/'),
        ),
        migrations.AddField(
            model_name='pesticidesandfertilizers',
            name='pest_image',
            field=models.FileField(blank=True, upload_to='pest_images/'),
        ),
        migrations.AddField(
            model_name='seed',
            name='seed_image',
            field=models.FileField(blank=True, upload_to='seed_images/'),
        ),
    ]
