# Generated by Django 2.2 on 2021-01-16 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0012_cropimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='crop_images',
        ),
    ]
