# Generated by Django 2.2 on 2021-01-20 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0013_remove_crop_crop_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='sell_flag',
        ),
    ]
