# Generated by Django 2.2 on 2021-03-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0013_auto_20210304_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='fertilizer_expense',
            field=models.IntegerField(blank=True, default=None, verbose_name='Fertilizer Expense'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='machine_expense',
            field=models.IntegerField(blank=True, default=None, verbose_name='Machine Expense'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='seed_expense',
            field=models.IntegerField(blank=True, default=None, verbose_name='Seed Expense'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='total_expense',
            field=models.IntegerField(blank=True, default=None, verbose_name='Total Expense'),
            preserve_default=False,
        ),
    ]
