# Generated by Django 2.2 on 2021-03-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0014_auto_20210305_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropactivity',
            name='date',
            field=models.DateField(blank=True, default=None, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
