# Generated by Django 2.2 on 2021-01-20 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crop', '0014_remove_crop_sell_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crops', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crop.Crop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
