# Generated by Django 2.2 on 2021-03-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0015_cropactivity_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropactivity',
            name='date',
        ),
    ]
