# Generated by Django 2.2 on 2021-03-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0018_auto_20210305_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='acres',
            field=models.CharField(max_length=30, verbose_name='Acres'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='crop_image',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='crop_name',
            field=models.CharField(max_length=30, verbose_name='Crop Name'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='exp_harvest_date',
            field=models.DateField(verbose_name='Expected Harvest Date'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='exp_price',
            field=models.IntegerField(verbose_name='Expected Price'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='exp_yield',
            field=models.CharField(max_length=30, verbose_name='Expected Yield'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='harvest_days',
            field=models.IntegerField(verbose_name='Harvest Days'),
        ),
    ]
