# Generated by Django 2.2 on 2021-03-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0019_auto_20210305_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropactivity',
            name='activity',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cropactivity',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
