# Generated by Django 2.2 on 2021-03-06 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0022_buyrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
