# Generated by Django 2.2 on 2021-03-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0023_buyrequest_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyrequest',
            name='approve',
        ),
        migrations.AlterField(
            model_name='buyrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('reject', 'Reject')], default='pending', max_length=20),
        ),
    ]
