# Generated by Django 2.2 on 2021-03-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0024_auto_20210306_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
