# Generated by Django 2.2 on 2021-03-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0026_remove_buyrequest_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='total_amount',
            field=models.IntegerField(blank=True, default=None, verbose_name='Total Amount'),
            preserve_default=False,
        ),
    ]
