# Generated by Django 2.2 on 2021-03-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0027_buyrequest_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyrequest',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Amount'),
        ),
    ]
