# Generated by Django 2.2 on 2021-03-06 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0028_auto_20210306_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyrequest',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
