# Generated by Django 2.2 on 2020-12-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201223_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='Mobile',
            field=models.BigIntegerField(unique=True),
        ),
    ]
