# Generated by Django 2.2 on 2021-01-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201223_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_images',
            field=models.ImageField(default=None, upload_to='uploads/profile-images'),
            preserve_default=False,
        ),
    ]
