# Generated by Django 2.2 on 2021-01-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_usercredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredit',
            name='credit_amt',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='usercredit',
            name='used_amt',
            field=models.BigIntegerField(default=0),
        ),
    ]
