# Generated by Django 2.2 on 2021-01-10 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210109_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_credit', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
