# Generated by Django 2.2 on 2021-01-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210110_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredit',
            name='balance_amt',
            field=models.BigIntegerField(default=0),
        ),
    ]
