# Generated by Django 2.2 on 2021-01-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_usercredit_balance_amt'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='usercredit',
            name='credit_amt',
        ),
        migrations.AddField(
            model_name='usercredit',
            name='credit_amt',
            field=models.ManyToManyField(to='user.test'),
        ),
    ]
