# Generated by Django 2.2 on 2021-01-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210110_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercredit',
            name='credit_amt',
        ),
        migrations.AddField(
            model_name='usercredit',
            name='credit_amt',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
