# Generated by Django 2.2 on 2021-01-10 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210110_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='usercredit',
            name='credit_amt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.test'),
        ),
    ]
