# Generated by Django 2.2 on 2021-01-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210110_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredit',
            name='credit_amt',
            field=models.BigIntegerField(),
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
