# Generated by Django 2.2 on 2021-01-10 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20210110_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercredit',
            old_name='credit_amt',
            new_name='total_credit_amt',
        ),
    ]
