# Generated by Django 2.2 on 2021-01-11 14:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210110_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_transaction', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(choices=[('credit', 'CREDIT'), ('debit', 'DEBIT')], default='credit', max_length=6)),
                ('purpose', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transaction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserCredit',
        ),
    ]
