# Generated by Django 2.2 on 2021-01-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20210111_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_images',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/profile-images'),
        ),
    ]
