# Generated by Django 2.2 on 2021-01-22 12:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20210120_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trans_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
