# Generated by Django 2.2 on 2021-01-22 12:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20210122_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
