# Generated by Django 2.2 on 2021-01-16 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(choices=[('agronomist', 'Agronomist'), ('soil-test', 'Soil Test'), ('crop-advice', 'Crop Advice'), ('tech-fin-aid', 'Technical Financial Aid')], default='agronomist', max_length=6)),
                ('remark', models.TextField(blank=True, max_length=30, verbose_name='Remarks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_service', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
