# Generated by Django 2.2 on 2021-01-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='services',
            field=models.CharField(choices=[('agronomist', 'Agronomist'), ('soil-test', 'Soil Test'), ('crop-advice', 'Crop Advice'), ('tech-fin-aid', 'Technical Financial Aid')], default='agronomist', max_length=20),
        ),
    ]
