# Generated by Django 2.2 on 2021-03-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20210305_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='date',
        ),
    ]
